"""Formats the mutation results written by RunMutationTests.ps1.

Usage: python SummarizeMutations.py
Reads ../Measurements/MutationResults.json and, when present,
../Measurements/MutationResultsTrack005.json. Writes Mutations.md.
"""

import json
from pathlib import Path

ANALYSIS_DIRECTORY = Path(__file__).resolve().parent
MEASUREMENTS = ANALYSIS_DIRECTORY.parent / "Measurements"

# Judgement of what each change does to answers, from reading the changed code.
EFFECT = {
    "Unmodified": "None; control",
    "RadiusIgnoresShorterExtent": "Missed contacts on every track",
    "RadiusShortByTenth": "Missed contacts on every track",
    "RadiusShortByHundredth": "Missed contacts on every track, rarely",
    "RadiusShortByThousandth": "Missed contacts on every track, rarely",
    "RadiusWithoutRoundingMargin": "Missed contacts within one rounding step of a cell boundary",
    "MaximumColumnOmitsRadius": "Missed contacts on every track",
    "LastCandidateSkipped": "Missed contacts on every track",
    "SupportsIgnoresBoundsLimit": "Missed contacts for footprints larger than the indexed one",
    "CenteredLookupUsesOrigin": "Missed contacts for footprints with a shifted origin",
    "ClosingEdgeTargetsSecondVertex": "Wrong closing edge on every outline",
    "RotationDirectionReversed": "Wrong rectangle for every nonzero yaw",
    "FourthSideNotTested": "Missed contacts on one rectangle side",
    "EndpointContactExcluded": "Missed contacts only for rectangles rounded to zero width",
    "CrossingUsesEitherStraddle": "False contacts on every track",
    "TouchingBoundsDoNotOverlap": "Missed contacts that touch along an axis",
    "ErrorBoundFarTooSmall": "Wrong signs only for nearly collinear points with wide exponent ranges",
    "ExactFallbackReturnsZero": "Wrong signs for nearly collinear points",
    "BoundedIntegerShiftTooWide": "Wrong signs for exponent spans of 38 to 60",
    "SubnormalCheckRemoved": "None; behavior preserving",
    "CenterGridExpansionDropped": "Missed contacts on tracks that use the fallback grid",
    "TreeVisitsLeftChildOnly": "Missed contacts on tracks that use the long-edge tree",
    "TreeLeafSkipsLastEdge": "Missed contacts on tracks that use the long-edge tree",
    "SparseCellsSkipLastRow": "Missed contacts on tracks that use the sparse fallback grid",
}


def render_table(headers, rows, right_aligned=()):
    widths = [len(header) for header in headers]
    for row in rows:
        for index, cell in enumerate(row):
            widths[index] = max(widths[index], len(cell))

    def render_row(cells):
        padded = []
        for index, cell in enumerate(cells):
            padded.append(cell.rjust(widths[index]) if index in right_aligned else cell.ljust(widths[index]))
        return "| " + " | ".join(padded) + " |"

    separators = []
    for index, width in enumerate(widths):
        separators.append("-" * (width - 1) + ":" if index in right_aligned else "-" * width)
    lines = [render_row(headers), "| " + " | ".join(separators) + " |"]
    lines.extend(render_row(row) for row in rows)
    return "\n".join(lines)


def outcome(value):
    return {"Pass": "Missed", "Fail": "Detected", "Timeout": "Timed out", "": "Not run"}[value]


def main():
    results = json.loads((MEASUREMENTS / "MutationResults.json").read_text(encoding="utf-8-sig"))
    rows = []
    detected = 0
    survivors = []
    for result in results:
        if result["Name"] == "Unmodified":
            continue
        stages = [result["OriginalSuite"], result["RibeyeSuite"], result["ExtendedSuite"]]
        caught = "Fail" in stages
        detected += caught
        if not caught:
            survivors.append(result["Name"])
        rows.append([
            result["Name"],
            result["Path"],
            outcome(result["OriginalSuite"]),
            outcome(result["RibeyeSuite"]),
            outcome(result["ExtendedSuite"]),
            EFFECT[result["Name"]],
        ])

    sections = [
        "# Mutation results",
        "",
        "Generated by `SummarizeMutations.py`.",
        f"Defects injected: {len(rows)}. Detected by at least one suite: {detected}. Missed by all: {len(survivors)}.",
        "",
        "## Existing suites with their own data",
        "",
        render_table(
            ["Injected defect", "Code path", "Original suite", "Ribeye suite", "Extended suite",
             "Effect on answers"],
            rows),
        "",
    ]

    substituted = MEASUREMENTS / "MutationResultsTrack005.json"
    if substituted.exists():
        rows = []
        for result in json.loads(substituted.read_text(encoding="utf-8-sig")):
            if result["Name"] == "Unmodified":
                verdict = "Passes" if result["RibeyeSuite"] == "Pass" else "Fails"
            else:
                verdict = outcome(result["RibeyeSuite"])
            rows.append([
                result["Name"],
                result["Path"],
                verdict,
                result["RibeyeFailure"].replace("FAIL: System.InvalidOperationException: ", "") or "none",
            ])
        sections += [
            "## Ribeye suite with Track005 data in place of Ribeye data",
            "",
            render_table(["Injected defect", "Code path", "Ribeye suite", "First failure"], rows),
            "",
        ]

    text = "\n".join(sections)
    (ANALYSIS_DIRECTORY / "Mutations.md").write_text(text, encoding="utf-8", newline="\n")
    print(text)


if __name__ == "__main__":
    main()
